#We require root permissions in order to run docker containers
sudo: required
# we define the list of services that should be started
services: 
  - docker
#commands to be executed before run our tests
before_install:
  - docker build -t diegollorente/docker-react -f Dockerfile.dev .

script:
  - docker run diegollorente/docker-react npm run testCI