#We require root permissions in order to run docker containers
sudo: required
# we define the list of services that should be started
services: 
  - docker
#commands to be executed before run our tests
before_install:
  - docker build -t diegollorente/docker-react -f Dockerfile.dev .

script:
  - docker run diegollorente/docker-react npm run testCI

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  #S3 instance for having access to the persistence
  bucket_name: "elasticbeanstalk-us-east-2-786178166797"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY  
  secret_access_key:
    secure: "$AWS_SECRET_KEY"